---
dist: bionic

language: python

python:
- "3.7"

env:
- ENGINE=podman

services: docker

before_install:
- src/scripts/install_singularity.sh
- src/scripts/install_podman.sh
- pip install coverage

install:
- pip install src/[dev]
- black --check --diff .

script:
# run tests
# - coverage run -m unittest -v src/test/test_*
# generate versioning file (src/popper/_version.py)
# - popper version
# run docker image pipeline
# - popper run --allow-undefined-secrets-in-ci
- podman run -d debian:buster-slim sleep 20000 -q
- podman run -d alpine:3.9 sleep 10000 -q
- podman container ls -a
- sleep 40000
- podman container ls -a
# after_success:
# - bash <(curl -s https://codecov.io/bash)
